title: Jingjin Hu's Homepage
description:
show_downloads: false
theme: 
github:
  is_project_page: false
  project_tagline:
# baseurl: ./

# markdown: kramdown
# highlighter: rouge

exclude: [README.md]