title: Jingjin Hu's Homepage
description:
show_downloads: false
theme: 
github:
  is_project_page: false
  project_tagline:
homurl: https://JennyHu96.github.io

# markdown: kramdown
# highlighter: rouge

exclude: [README.md]